// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA076npYp-IWblVUKigW2lxAMn2z9UbyYM',
    appId: '1:246309926426:web:e423939d268662681903a3',
    messagingSenderId: '246309926426',
    projectId: 'car-reels',
    authDomain: 'car-reels.firebaseapp.com',
    databaseURL: 'https://car-reels-default-rtdb.firebaseio.com',
    storageBucket: 'car-reels.appspot.com',
    measurementId: 'G-BZ4DFDGTSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-MzdnrMxazztN5Au7-gC3VewHI7at74',
    appId: '1:246309926426:android:78e46dac0c3d5f981903a3',
    messagingSenderId: '246309926426',
    projectId: 'car-reels',
    databaseURL: 'https://car-reels-default-rtdb.firebaseio.com',
    storageBucket: 'car-reels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBcWHfu7JgUdYP32mY3IYdd3xKMPEUMe0',
    appId: '1:246309926426:ios:805ad4e530f8536c1903a3',
    messagingSenderId: '246309926426',
    projectId: 'car-reels',
    databaseURL: 'https://car-reels-default-rtdb.firebaseio.com',
    storageBucket: 'car-reels.appspot.com',
    iosClientId: '246309926426-15v4i1e8q89rdltt55u3r02olq3fbgp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carReels',
  );
}
